http://localhost:3000/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1
&q=preston


###

http://localhost:3000/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1
&month=aug

###

http://localhost:3000/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1
&next=7

###

https://betc-api-nfhtjvbwks.now.sh/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1


###

https://betc-api-nfhtjvbwks.now.sh/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1
&q=preston
###

https://betc-api-nfhtjvbwks.now.sh/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1
&month=mar

###

https://betc-api-nfhtjvbwks.now.sh/api
?id=1yTj5mU3EnR4AesESbDNOEU3B0GV8Nox_z0PnkSgHxpw
&integers=false
&columns=false
&sheet=1
&next=6